---

- name: Install list of packages
  apt: 
    name:
      - apache2
    state: present

- name: Create directory /run/lock for apache2
  file: 
    path: /run/lock 
    state: directory

- name: Start services
  systemd: 
    name: httpd.service
    state: started
